### ISSUE TITLE
Location of WG homepage

### ISSUE THREAD

**Issue by hober** [w3c/htmlwg#7]
As we all know, [cool URIs don't change](https://www.w3.org/Provider/Style/URI).

Our homepage really should be `https://www.w3.org/html/wg/` and not `https://www.w3.org/2019/html/`.

See also w3c/webappswg#26.

**Comment by plehegar** [comment]
note that the systeam folks have been working on a w3c datatracker (similar to the IETF one), which will make the current WG homepage obsolete. Once this gets shipped, we can return to this issue imho.

**Comment by siusin** [comment]
Oh, this bug was fixed a few months ago, https://www.w3.org/html/wg/ now redirects to the WG homepage. 

Can we close this issue?

**Comment by hober** [comment]
I'd much prefer `https://www.w3.org/html/wg/` to be the actual WG home page, and not a redirect.

**Comment by frivoal** [comment]
As of now, https://www.w3.org/html/wg/ redirects to https://www.w3.org/2019/html/, and https://www.w3.org/2019/html/ is a 404. Does the homepage of the WG still exist?

**Comment by siusin** [comment]
Thanks for reporting the bug!

The homepage is hosted in the GitHub repo(index.html). The link broke when we renamed the branch. Now https://w3c.github.io/htmlwg/ is working, I'll ask the systeam to re-activate the redirects (/html/wg/ and /2019/html/)

**Comment by siusin** [comment]
These broken links have been fixed. Thanks.

**Comment by plehegar** [comment]
I suggest changing the homepage of the Group to use https://www.w3.org/groups/wg/htmlwg

It's generic and not flexible but is there additional information?

**Comment by siusin** [comment]
The URL of the homepage has been updated in the system -> https://www.w3.org/groups/wg/htmlwg
